### ISSUE TITLE
Strange problem in mgmotionaverage

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#24]
Running mgmotionaverage on a normal video file works fine, but when running on a motion video I get the following problem: 

> Error using set
> Expected CurrentTime to be a scalar with value <= 62.8.
>
> Error in audiovideo.internal.IVideoReader/set.CurrentTime (line 403)
>                validateattributes( timeInSecs, {'double'}, ...
>
> Error in mgmotionaverage (line 130)
>            mg.video.obj.CurrentTime = (1/mg.video.obj.FrameRate)*indf;

**Comment by emoninet2** [comment]
How do i replicate this error?

**Comment by emoninet2** [comment]
I faced similar error in mgmotionhistory which I have fixed in https://github.com/fourMs/MGT-matlab/pull/25. I have made similar fix changes on mgmotion and mgmotionaverage. However, I could not replicate this error on mgmotionaverage, but please check and let me know if this error is resolved or still persists.
